version: 2
snapshot:
  widths:
    - 1280
  minHeight: 1024
  percyCSS: ''
  enableJavaScript: false
  cliEnableJavaScript: true
  disableShadowDOM: false
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 750
  launch-options:
    headless: true
upload:
  files: '**/*.{png,jpg,jpeg}'
  ignore: ''
  stripExtensions: false
